camera_matrix:
- - 523.4521729667503
  - 0.0
  - 304.40696130043284
- - 0.0
  - 523.9812351771714
  - 241.39147259799498
- - 0.0
  - 0.0
  - 1.0
distortion_coefficients:
- - -0.06791727503156242
  - 0.31777916031901016
  - 0.001977324586923682
  - -0.00022093876126441382
  - -0.4282522003256911
image_height: 480
image_width: 640
mean_reprojection_error: 0.026659341686999013
new_camera_matrix:
- - 509.3377685546875
  - 0.0
  - 301.05515341208957
- - 0.0
  - 507.2577209472656
  - 242.4840435758788
- - 0.0
  - 0.0
  - 1.0
roi:
  height: 466
  width: 625
  x: 4
  y: 7
